### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by JKoss2** [tushardhadiwal/homebridge-levoitcore-client#1]
Is it possible to add functionality for the sleep feature, and the timer feature? I don’t know if the API allows for it, I’m having a hard time finding it online. (Unless I am misunderstanding how this plugin works)

It’d be nice to have a automation that turns it to sleep mode when it occurs or say when I leave home, it turns it on to a selected fan speed for x amount of time. 

Maybe a notification of filter life too?

**Comment by tushardhadiwal** [comment]
@BackWoodsBoy941 You can use Turn On Turn off feature with ios automation based on geo location. For other time based automation, you can set it once through VeSync App. As far I know, Homekit API does not support this at the moment. Homekit API also does not support Sleep Mode at the moment.

Filter life notification comes through VeSync App, since Filter replacement is once in a 6 month process, development for notification may not be worth it at the moment. Thanks for Feature suggestions!
